name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-secrets:
    name: Check Secrets
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Check for required secrets
        run: |
          if [[ -z "${{ secrets.CF_API_TOKEN }}" || -z "${{ secrets.CF_ACCOUNT_ID }}" ]]; then
            echo "ERROR: Required secrets are missing!"
            echo "Please set CF_API_TOKEN and CF_ACCOUNT_ID in repository secrets"
            exit 1
          fi
          echo "All required secrets are present"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: check-secrets
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npx opennextjs-cloudflare build

      - name: Deploy to Cloudflare Workers
        run: npx opennextjs-cloudflare deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

  preview:
    name: Preview
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npx opennextjs-cloudflare build

      - name: Preview
        run: npx opennextjs-cloudflare preview
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}