name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install TypeScript type definitions
      run: |
        npm install --save-dev @types/wow.js || echo "@types/wow.js not available, using custom declaration"

    - name: Build application
      run: npx @opennextjs/cloudflare build
      env:
        NODE_ENV: production

    - name: Deploy to Cloudflare Workers
      run: |
        npx wrangler deploy --env production
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      if: github.ref == 'refs/heads/main'

    - name: Deploy to Cloudflare Workers Preview
      run: |
        npx wrangler deploy --env preview
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      if: github.event_name == 'pull_request'